//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace revGeneral
{
    using System;
    using System.Collections.Generic;
    
    public partial class entreprise
    {
        public entreprise()
        {
            this.employes = new HashSet<employe>();
        }
    
        public int code { get; set; }
        public string name { get; set; }
        public string ville { get; set; }
    
        public virtual ICollection<employe> employes { get; set; }
    }
}
